# Generated by Django 5.2.6 on 2025-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
