# Generated by Django 5.2.6 on 2025-09-09 06:33

from django.db import migrations


def update_speed_field(apps, schema_editor):
    """Update existing records to have speed = 0.0"""
    GPSData = apps.get_model('iot', 'GPSData')
    GPSData.objects.filter(speed__isnull=True).update(speed=0.0)


def reverse_update_speed_field(apps, schema_editor):
    """Reverse operation - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_gpsdata_speed'),
    ]

    operations = [
        migrations.RunPython(update_speed_field, reverse_update_speed_field),
    ]
