# Generated by Django 5.2.6 on 2025-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20250909_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='course',
            field=models.FloatField(default=0.0),
        ),
    ]
