# Generated by Django 5.2.6 on 2025-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_gpsdata_altitude_gpsdata_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='ignitionstatus',
            field=models.BooleanField(default=False),
        ),
    ]
