# Generated by Django 5.2.6 on 2025-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_gpsdata_ignitionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('NODEMCU', 'NodeMCU'), ('NEO6M', 'NEO-6M'), ('SIM800L', 'SIM800L'), ('WIFI', 'WiFi')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING_GPS', 'Waiting for GPS location'), ('GPS_LOST', 'GPS lost'), ('LOW_BATTERY', 'Low battery'), ('NETWORK_ISSUE', 'Network issue'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
