# Generated by Django 5.2.6 on 2025-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_devicestatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('relay_state', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
